package ch09;

import java.util.Date;

import lombok.Getter;

@Getter
class Card {
	String pattern;
	String number;
	
	public Card(String pattern, String number) {
		this.pattern = pattern;
		this.number = number;
	}
	public Card(Card card) {
		this.pattern = card.pattern;
		this.number = card.number;
	}
}

class BetterCard extends Card {
	public BetterCard(String pattern, String number) {
		super(pattern, number);
		// TODO Auto-generated constructor stub
	}
	public BetterCard(Card card) {
		super(card);
	}
	@Override
	public String toString() {
		return "kind: " + pattern + ", number: " + number;
	}
}


class AutoGeneratedCard extends Card {
	public AutoGeneratedCard(Card card) {
		super(card);
		// TODO Auto-generated constructor stub
	}

	public AutoGeneratedCard(String pattern, String number) {
		super(pattern, number);
		// TODO Auto-generated constructor stub
	}

	@Override
	public String toString() {
		return "AutoGeneratedCard [pattern=" + pattern + ", number=" + number + "]";
	}
	
}

public class ToStringTest {
	public static void main(String[] args) {
		Card card = new Card("Spade", "J");
		String cardString = new String("Spade J");
		Date date = new Date();
		System.out.println(card);
		System.out.println(cardString);
		System.out.println(date);
		
		BetterCard betterCard = new BetterCard(card);
		System.out.println(betterCard);
		AutoGeneratedCard autoGeneratedCard = new AutoGeneratedCard(card);
		System.out.println(autoGeneratedCard);
	}
}
